### PR TITLE
Change version of software in appdata

### PR DESCRIPTION
**Pull request by JeffLabonte**

### CODE REVIEW

**Comment by JeffLabonte** [comment]
I have also removed them in the second commit :)

**Comment by TingPing** [comment]
Not what the webui shows: https://github.com/flathub/io.exodus.Exodus/pull/3/files

**Comment by TingPing** [comment]
Just squash it into a single commit, force push it.

**Comment by JeffLabonte** [comment]
I went and created a new branch then merged it to master. So the commit has no unwanted files in it.

**Pull request closed without merging**
