### PR TITLE
Update exodus to 19.10.18

### PR DESCRIPTION
**Pull request by dvreed**
Current version in flathub is two versions old.  Update to latest 19.10.18 released on Oct 18

### CODE REVIEW

**Comment by dvreed** [comment]
I am unable to test my change locally as I get a [SUID error](https://github.com/flatpak/flatpak/issues/3044) when trying to run the resulting build.  Is there something special you do to the flathub builds that gets around this electron error?

**Comment by TingPing** [comment]
You have to disable the sandbox, passing `--no-sandbox` to the launcher *may* work.

**Comment by dvreed** [comment]
It seems that it doesn't like it...  forgive me I'm a flathub newb
```
$  flatpak install --user https://dl.flathub.org/build-repo/9944/io.exodus.Exodus.flatpakref
$  flatpak run io.exodus.Exodus --no-sandbox
Gtk-Message: 13:43:15.759: Failed to load module "canberra-gtk-module"
Gtk-Message: 13:43:15.759: Failed to load module "pk-gtk-module"
Gtk-Message: 13:43:15.759: Failed to load module "canberra-gtk-module"
Gtk-Message: 13:43:15.759: Failed to load module "pk-gtk-module"
ENV: production
Can only pass whitelisted args; exiting

```
Whereas the one currently in flathub doesn't need extra arguments
```$  flatpak install flathub io.exodus.Exodus
$  flatpak run io.exodus.Exodus
Gtk-Message: 13:44:44.642: Failed to load module "canberra-gtk-module"
Gtk-Message: 13:44:44.642: Failed to load module "pk-gtk-module"
Gtk-Message: 13:44:44.642: Failed to load module "canberra-gtk-module"
Gtk-Message: 13:44:44.642: Failed to load module "pk-gtk-module"
ENV: production
(node:2) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Exodus (production): DATA DIR: /home/dareed/.var/app/io.exodus.Exodus/config/Exodus
main: 1060.076ms
Using wasm:  true

SET WALLET LOADED action: null loadedFrom: passphrase
true

```

**Comment by TingPing** [comment]
You'll have to dig into how the electron launcher works. Being proprietary its possible this is a very annoying problem to solve if they whitelist things in their app.

**Comment by AHappyUser** [comment]
In release 19.10.11 Exodus added a new file called "chrome-sandbox".
When running the test build I get an error with that file name.

`[admin@fedora Test]$ flatpak run io.exodus.Exodus
[2:1024/153718.015839:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /app/extra/chrome-sandbox is owned by root and has mode 4755. `

I hope this is helpful!

**Comment by TingPing** [comment]
Closing in favor of #41

**Pull request closed without merging**
