### PR TITLE
Update to Version 21.11.24

### PR DESCRIPTION
**Pull request by tomaswarynyca**

### CODE REVIEW

**Comment by AHappyUser** [comment]
@tomaswarynyca Thank again for the update!

**Comment by AHappyUser** [comment]
@tomaswarynyca If you would like we can ask [TingPing](https://github.com/TingPing) to give you wright access to this repository.

**Comment by tomaswarynyca** [comment]
@AHappyUser as you wish, so I don't have to bother you :+1:

**Comment by AHappyUser** [comment]
@TingPing  [tomaswarynyca](https://github.com/tomaswarynyca) has submitted several updates to the Exodus repository.  Can you allow [tomaswarynyca](https://github.com/tomaswarynyca) to submit pull requests.

**Comment by TingPing** [comment]
Sure, invite sent.

**Comment by tomaswarynyca** [comment]
I have just accepted the invitation, thanks @AHappyUser @TingPing :smile:

**Pull request merged**
