### PR TITLE
Add `x-checker-data` to exodus zip

### PR DESCRIPTION
**Pull request by FakeShemp**

### CODE REVIEW

**Comment by AHappyUser** [comment]
I would love to know more about x-checker-data.  Will it automatically update the package?

**Comment by FakeShemp** [comment]
It will automatically check for updates and create a pull request if it finds an update. It can also be configured to automatically merge the request if the build passes, but that isn't done in this PR.

**Comment by FakeShemp** [comment]
@AHappyUser https://github.com/flathub/flatpak-external-data-checker

**Comment by AHappyUser** [comment]
@FakeShemp  Thanks for the info! This seems like a great idea.

**Pull request merged**
